name: Use Docker Based Action

on:
  push:
    branches: [ main ]

jobs:
  docker-action-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Custom Docker Action
        uses: ./
        with:
          name: Priya
